### ISSUE TITLE
DeepCGP is not working!

### ISSUE THREAD

**Issue by ahx-code** [kekeblom/DeepCGP#2]
I tried two simple steps.

Step #1: python conv_gp/mnist.py -> ModuleNotFoundError:
Step #2: The read_args method have missing arguments such as M, N, test_size variables.

Could you please upload a working version.

**Comment by ahx-code** [comment]
Following flags were not initialized:

test-size 
load_model
global_step
lr_decay_steps

**Comment by kekeblom** [comment]
What version of python are you using? Which module was not found?

**Comment by ahx-code** [comment]
I'm currently using python 3.6.6. I solved the module not found problem.

However, inside the mnist.py-> https://github.com/kekeblom/DeepCGP/blob/master/conv_gp/mnist.py 

If you look at the _select_test_points() method, there is a ''self.flags.test_size'' variable, which was not initialized inside the read_args() method.

Same, if you look at: https://github.com/kekeblom/DeepCGP/blob/master/conv_gp/experiment.py

_setup_model() method, ''self.flags.load_model'' variable was not initialized.

There are two more uninitialized falg variables: ''self.flags.global_step'', and ''self.flags.lr_decay_steps''.

I think if you update the read_args() method with the following initialized variables, the problem will be solved.

Thanks.

**Comment by ahx-code** [comment]
Dear Kenneth, 

When you were testing, how long did the tests take?

Also did you have any allocation problem? (Like below)

<img width="868" alt="Screen Shot 2019-07-21 at 00 23 01" src="https://user-images.githubusercontent.com/8464220/61584292-d1129c00-ab4d-11e9-8f2c-9f4327aff129.png">

**Comment by kekeblom** [comment]
No I did not have an allocation problem. The warning means that you are running low on memory. Either decrease the batch size, inducing point count or get access to more memory and you should be good. You can also try running it on the cpu.

The mnist 2 layer takes maybe 24 hours to run.
