### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'load_model'

### ISSUE THREAD

**Issue by ahx-code** [kekeblom/DeepCGP#3]
In experiment.py, _setup_model method throws the attribute error:

`def _setup_model(self):`

`model_builder = ModelBuilder(self.flags, self.X_train, self.Y_train,   
                                                    model_path=self._model_path(self.flags.load_model))`

`        self.model = model_builder.build()`

The flag variable load model was not defined in the cifar.py, read_args() method.

How should I declare load_model variable?

**Comment by kekeblom** [comment]
In the `read_args` method, `default_parser` is called in which the `load-model` argument is defined. Make sure that function is getting imported correctly on your setup.

**Comment by AhmetTavli** [comment]
Thanks for the answer, I did check as you suggested me, however I couldn't find it. Am I missing something?

<img width="934" alt="Screen Shot 2019-07-17 at 10 43 12" src="https://user-images.githubusercontent.com/8464220/61356999-1f8b1680-a880-11e9-8a97-c967c58b3877.png">
